name: Deploy to Cloud Run

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set Up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

            - name: Configure Docker to use gcloud
              run: |
                  gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

            - name: Build and Push Docker Image
              run: |
                  export IMAGE_TAG=$(git rev-parse --short ${{ github.sha }})
                  export IMAGE_NAME=asia-southeast2-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_ARTIFACTS_REPOSITORY }}/cloud-run-github-actions:${IMAGE_TAG}
                  docker build -t ${IMAGE_TAG} .
                  docker push ${IMAGE_NAME}

            - name: Deploy to Cloud Run
              run: |
                  export IMAGE_TAG=$(git rev-parse --short ${{ github.sha }})
                  export IMAGE_NAME=asia-southeast2-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_ARTIFACTS_REPOSITORY }}/cloud-run-github-actions:${IMAGE_TAG}
                  gcloud run deploy cloud-run-github-actions --image ${IMAGE_NAME} --region asia-southeast2 --allow-unauthenticated
